### ISSUE TITLE
Shorted PIRs ?

### ISSUE THREAD

**Issue by N3-Franz** [circa10a/pumpkin-pi#1]
It would seem from the circuit diagram that the outputs of the PIRs are shorted to ground.  (circled in red - attached
![short pumpkin](https://user-images.githubusercontent.com/45132039/134051063-07ffd309-da6c-4a45-80de-ab875275aed2.PNG)
) 
not sure that image actually attached but follow the leads - those dots on the diagram clearly mean connection - both are pulled to ground.

**Comment by circa10a** [comment]
Hey @N3-Franz thanks for raising the issue! I've updated the diagram, can you please verify?

**Comment by N3-Franz** [comment]
I think that gets it - I've not of course built it, but now it makes sense. And thank you for posting a fun project !
